---
  - name: Baseline Config for etc/deployment-apps directory
    hosts: standalone
    become: true
    strategy: free
    tasks:
      - name: Copying baseline config apps to etc/deployment-apps directory on standalone
        copy:
          src: "./AppDeploymentBundle/splunk_config_baseline/{{ item }}"
          dest: "/opt/splunk/etc/deployment-apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - org_all_deploymentclient
          - org_all_forwarder_outputs
          - org_all_forwarder_outputs_ssl
          - org_all_indexes
          - org_all_search_base
          - org_full_license_server
          - org_search_volume_indexes
          - org_all_indexer_base
          - org_test_forwarder_inputs
          - org_all_hf_inputs
          - org_all_hf_outputs
          - org_all_syslog_inputs
        tags:
          - standalone
          - deployment

      - name: Copying cluster baseline config apps to etc/deployment-apps directory on standalone
        copy:
          src: "./AppDeploymentBundle/splunk_config_index_cluster/{{ item }}"
          dest: "/opt/splunk/etc/deployment-apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - org_cluster_forwarder_outputs
          - org_master_deploymentclient
          - org_cluster_forwarders_indexerDiscovery_outputs
          - org_multisite_master_base
          - org_cluster_indexer_base
          - org_cluster_search_base
          - org_site_1_forwarder_affinity
          - org_site_2_forwarder_affinity
          - org_cluster_master_base
          - org_cluster_master_indexerDiscovery_server
        tags:
          - standalone
          - deployment-cluster

      - name: Copy baseline non cluster .conf directories to etc/apps on standalone
        copy:
          src: "./AppDeploymentBundle/splunk_config_baseline/{{ item }}"
          dest: "/opt/splunk/etc/apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - org_all_indexes
          - org_all_standalone_indexer_base
          - org_indexer_volume_indexes
          - org_all_search_base_web
        tags:
          - standalone

      - name: Copy baseline custom apps to etc/apps
        copy:
          src: "./AppDeploymentBundle/custom_apps/{{ item }}"
          dest: "/opt/splunk/etc/apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - nrde_csa_ip_list
          - org_hec_indexer_inputs
        tags:
          - standalone

      - name: Copy downloaded  apps to etc/apps
        copy:
          src: "./AppDeploymentBundle/DownloadedApps/{{ item }}"
          dest: "/opt/splunk/etc/apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - Splunk_TA_f5-bigip
        tags:
          - standalone
          - downloaded

      - name: Copy downloaded  apps to etc/apps
        copy:
          src: "./AppDeploymentBundle/DownloadedApps/{{ item }}"
          dest: "/opt/splunk/etc/deployment-apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - Splunk_TA_f5-bigip
        tags:
          - standalone
          - downloaded
