---
  - name: copy baseline splunk configurations
    hosts: dfs shs
    become: true
    strategy: free
    tasks:
      - name: Copy non cluster baseline .conf directories to DMC's apps directory
        copy:
          src: "./AppDeploymentBundle/splunk_config_baseline/{{ item }}"
          dest: "/opt/splunk/etc/apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - org_all_deploymentclient

      - name: install java
        yum:
          name:
            - java-1.8.0-openjdk
          state: latest
          update_cache: yes

      - shell: echo JAVA_HOME is $JAVA_HOME
        environment:
          JAVA_HOME: /bin/java
          java_home: /bin/java
          SPLUNK_HOME: /opt/splunk 
        register: shellout
        tags:
          - env
      - debug: var=shellout
