---
  - name: copy baseline splunk configurations
    hosts: idxrs_site1
    become: true
    strategy: free
    tasks:
      - name: BootStrap Indexers with baseline cluster config
        copy:
          src: "./AppDeploymentBundle/splunk_config_baseline/{{ item }}"
          dest: "/opt/splunk/etc/apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - org_all_deploymentclient_site1
