---
  - name: copy baseline splunk configurations
    hosts: cms
    become: true
    strategy: free
    tasks:
      - name: Copy non cluster baseline .conf directories to DMC's apps directory
        copy:
          src: "./AppDeploymentBundle/splunk_config_baseline/{{ item }}"
          dest: "/opt/splunk/etc/apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - org_all_deploymentclient
