---
  - name: copy baseline splunk configurations
    hosts: cms
    strategy: free
    become: true
    tasks:
      - name: Copy non cluster baseline .conf directories to cluster master apps directory
        copy:
          src: "./AppDeploymentBundle/splunk_config_baseline/{{ item }}"
          dest: "/opt/splunk/etc/apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - org_all_forwarder_outputs
          - org_search_volume_indexes
          - org_all_search_base
          - org_all_search_base_web
          - org_all_indexes

      - name: Copy cluster baseline .conf directories to cluster master apps directory
        copy:
          src: "./AppDeploymentBundle/splunk_config_index_cluster/{{ item }}"
          dest: "/opt/splunk/etc/apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - org_multisite_master_base
          - org_cluster_master_base

      - name: Copy cluster baseline .conf directories to cluster master master-apps directory
        copy:
          src: "./AppDeploymentBundle/splunk_config_baseline/{{ item }}"
          dest: "/opt/splunk/etc/master-apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - org_all_indexes
          - org_all_indexer_base
          - org_indexer_volume_indexes
          
      - name: Copy cluster baseline .conf directories to cluster master master-apps directory
        copy:
          src: "./AppDeploymentBundle/splunk_config_index_cluster/{{ item }}"
          dest: "/opt/splunk/etc/master-apps/"
          owner: splunk
          group: splunk
          mode: 0755
        with_items:
          - org_cluster_indexes_base
