---
  - name: Create Splunk Data Volume
    hosts: idxrs
    become: true
    strategy: free
    tasks:
      - name: install lvm2
        yum:
          name:
            - lvm2
            - gcc
            - nvme-cli
            - xfsprogs
          state: latest
          update_cache: yes

      - name: Create Volume Group vg_splunkdata
        lvg:
          pvs: "{{ splunk_disks }}"
          vg: vg_splunkdata

      - name: Create a logical volume
        lvol:
          vg: vg_splunkdata
          lv: lv_splunkdata
          size: +100%FREE

      - name: create file system for lv_splunkdata
        filesystem:
              fstype: xfs
              dev: /dev/vg_splunkdata/lv_splunkdata

      - name: create data directory
        file:
           path: /splunkdata
           state: directory
           owner: splunk
           group: splunk
           mode: 0755

      - name: mount lv_splunkdata logical volume
        mount:
          name: /splunkdata
          src: /dev/vg_splunkdata/lv_splunkdata
          fstype: xfs
          state: mounted

      - name: create data directory
        file:
           path: /splunkdata
           state: directory
           owner: splunk
           group: splunk
           mode: 0755
