---
  - name: run bash script to install splunk enterprise
    hosts: sc4u_hosts
    become: true
    tasks:
      - name: run bash script to install splunk
        script: ../scripts/splunk_uf_install.sh
