---
  - name: Remove borked directory from Splunk server
    hosts: idxrs dfs shs
    become: true
    strategy: free
    vars:
      app : "{{ app }}"
    tasks:

    - name: Splunk delete etc/app directory
      file:
        path: "/opt/splunk/etc/apps/{{ item }}"
        state: absent

    - name: Restarting Splunk Enterprise Services with DEBUG ENABLED
      command: "/opt/splunk/bin/splunk restart"
      register: splunk

    - debug:
       var: splunk.stdout_lines
