---
  - name: Clean Event Data from index
    hosts: idxrs
    become: true
    become_user: splunk
    vars:
      splunk_admin: "{{ splunk_admin }}"
      splunk_pw: "{{ splunk_pw }}"
      index: "{{ index }}"
    tasks:

    - name: Stopping Splunkd
      shell: |
        /opt/splunk/bin/splunk stop
      register: splunk

    - debug:
       var: splunk.stdout_lines

    - name: Cleaning Indexing
      shell: |
        /opt/splunk/bin/splunk clean eventdata -index {{ index }} -auth {{ splunk_admin }}:{{ splunk_pw }} -f
      register: splunk

    - debug:
       var: splunk.stdout_lines

    - name: Starting Splunk
      shell: |
        /opt/splunk/bin/splunk start
      register: splunk

    - debug:
       var: splunk.stdout_lines
